version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/tests"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "terraform"
    directory: "/tf"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "terraform"
    commit-message:
      prefix: "deps"
